### ISSUE TITLE
US not listed as country anymore

### ISSUE THREAD

**Issue by rdorsch** [AaronWard/covidify#28]
Many thanks for covidify, Aaron.

**Describe the bug**
It seems that covidify does not find data from the US anymore.

**To Reproduce**
I added print(country_list) in data_prep.py to see the candidates

rd@h370:~/tmp.nobackup/git/covid-19-analysis$ ./build/lib/covidify/pipeline.sh ./build/lib/covidify ~/tmp.nobackup/covidify git "US"
###
###
ENV: ./build/lib/covidify
OUTPUT FOLDER: /home/rd/tmp.nobackup/covidify
DATA SOURCE: git
COUNTRIES: US
###
###
git pull from https://github.com/CSSEGISandData/COVID-19.git
Getting sheets...
... importing data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:03<00:00, 21.24it/s]
['italy', 'mongolia', 'sweden', 'curacao', 'romania', 'central african republic', 'grenada', 'laos', 'japan', 'slovakia', 'mexico', 'martinique', 'cameroon', 'singapore', 'nicaragua', 'liechtenstein', 'guatemala', 'thailand', 'senegal', 'gabon', 'cape verde', 'belarus', 'angola', 'dominican republic', 'new zealand', 'puerto rico', 'faroe islands', 'sri lanka', 'the gambia', 'brazil', 'colombia', 'norway', 'maldives', 'kazakhstan', 'occupied palestinian territory', 'jordan', 'oman', 'australia', 'nigeria', 'saint barthelemy', 'libya', 'mayotte', 'poland', 'congo', 'luxembourg', 'montenegro', 'costa rica', 'hungary', 'seychelles', 'hong kong', 'bosnia', 'trinidad and tobago', 'vietnam', 'benin', 'malaysia', 'taiwan', 'monaco', 'saudi arabia', 'guinea', "cote d'ivoire", 'rwanda', 'greenland', 'united kingdom', 'switzerland', 'azerbaijan', 'canada', 'argentina', 'uruguay', 'uzbekistan', 'cabo verde', 'israel', 'togo', 'el salvador', 'ireland', 'guernsey', 'mauritius', 'ethiopia', 'greece', 'peru', 'ghana', 'aruba', 'madagascar', 'uganda', 'ecuador', 'palestine', 'armenia', 'cayman islands', 'morocco', 'mozambique', 'iran', 'others', 'channel islands', 'bolivia', 'gambia', 'guadeloupe', 'saint kitts and nevis', 'holy see', 'india', 'denmark', 'east timor', 'antigua and barbuda', 'ukraine', 'turkey', 'cuba', 'austria', 'papua new guinea', 'haiti', 'burkina faso', 'finland', 'belize', 'niger', 'georgia', 'panama', 'estonia', 'chile', 'spain', 'the bahamas', 'tanzania', 'mali', 'russia', 'russian federation', 'liberia', 'north macedonia', 'china', 'cyprus', 'eritrea', 'jamaica', 'kenya', 'belgium', 'iraq', 'nepal', 'pakistan', 'netherlands', 'namibia', 'serbia', 'kosovo', 'america', 'saint lucia', 'saint martin', 'moldova', 'kuwait', 'zambia', 'zimbabwe', 'bangladesh', 'vatican city', 'paraguay', 'malta', 'lithuania', 'honduras', 'dominica', 'bhutan', 'syria', 'bulgaria', 'venezuela', 'bahrain', 'qatar', 'macau', 'equatorial guinea', 'cambodia', 'french guiana', 'brunei', 'philippines', 'indonesia', 'eswatini', 'reunion', 'portugal', 'croatia', 'ivory coast', 'algeria', 'san marino', 'latvia', 'slovenia', 'germany', 'djibouti', 'fiji', 'mauritania', 'suriname', 'guinea-bissau', 'south korea', 'guyana', 'saint vincent and the grenadines', 'jersey', 'south africa', 'somalia', 'united arab emirates', 'lebanon', 'guam', 'iceland', 'egypt', 'france', 'czechia', 'diamond princess', 'gibraltar', 'albania', 'afghanistan', 'kyrgyzstan', 'sudan', 'barbados', 'andorra', 'tunisia', 'st. martin', 'chad', 'timor-leste']
Country specified!
US was not listed.
rd@h370:~/tmp.nobackup/git/covid-19-analysis$

**Comment by AaronWard** [comment]
There is already an option to list possible countries using the command 

```
covidify list --countries
```

As for the US, the datasource changes the way they denote the US so much (America, united states of, USA, US, United state of america etc.) so i just parsed all the possible ways they make their entries to be just `America`

So if you just run `covidify run --country="America"` this should work

**Comment by creeble** [comment]
Wow, it's insane that the reporting is so random.  Thanks for fixing this; perhaps now I can look at doing US-state data breakouts.
