### ISSUE TITLE
Suggestion: Remove contradictory and misleading tags

### ISSUE THREAD

**Issue by funkyfuture** [AaronWard/covidify#29]
you're using misleading tags on this repository:

- `covid-virus`
  - there's no such thing, there's a virus mentioned below and an illness `covid-19` caused by it
- `wuhan`, `china`
  - this is not a local event, it's a `pandemic`
- `wuhan-virus`
  - its name is `SARS-CoV-2`
  - this term is used by nationalist circles, led by an orange maniac, in the United States of America only

please, from a European perspective how this pandemic is addressed and handled on the other side of the pond, is not comprehensible and very frightening. framings that deny the impact on any population do not make sense and are a danger b/c people are acting irresponsible when misinformation is spread by the authorities.

stay safe and protect others! speak scientific truth, not nationalist bigotry!

**Comment by funkyfuture** [comment]
oh dear, you're from this side of the pond.

**Comment by AaronWard** [comment]
@funkyfuture Those repo/tags were made this virus was contained to just china. 
But either way, the reason why it was referred to as a Wuhan virus was (you guessed it) originated in Wuhan. The same way the Zika virus originated in Zika and Ebola virus was originated in Ebola.

Its just a name. There is nothing "nationalist" about it, and thinking that it is is just mental gymnastics. These issues are not for political debate.  

Thank you, closing this issue.

**Comment by funkyfuture** [comment]
> The repo/tags were made when this virus was contained to just china.

and yet, you added the `pandemic` tag since it became one

> There is nothing "nationalist" about it

have you watched American government press conferences recently? it is used for nationalist narratives.

> thinking that it is is just mental gymnastics. These issues are not for political debate.

i'd call it science. and that must include a perspective on the political dimensions of an issue.
