### ISSUE TITLE
Cumulative trendline decreases

### ISSUE THREAD

**Issue by atitus** [AaronWard/covidify#31]
For US data, the cumulative trendline for confirmed cases decreases on some days. (Recovereds decreases on some days as well.)

![America_confirmed_trendline](https://user-images.githubusercontent.com/1793782/77839249-12c9fc80-7149-11ea-9f38-ffa15c2cc417.png)

For example, covidify shows 33 confirmed cases on 2020-03-13. I'm using the data_exploration.ipynb notebook.

**Comment by AaronWard** [comment]
The code in the notebook is out of date and buggy. They shouldn't be used as they are only used for testing out new features

This is how it looks using the python package 

![image](https://user-images.githubusercontent.com/22074246/77899909-283c4500-7275-11ea-9467-6820cf301554.png)

**Comment by atitus** [comment]
Thanks for the helpful reply. That's exactly what I needed. And thank you for the great package. 

I decided to get the data from the report and work with that data directly. That was exactly what I needed, since my application is very simple and is used in teaching.

I wonder if it's worth generating a report, similar to the spreadsheet, that only has the data in a csv format.

Once again, thank you for your work on this project.

**Comment by AaronWard** [comment]
> I wonder if it's worth generating a report, similar to the spreadsheet, that only has the data in a csv format.

@atitus in the `covidify-output/data/` folder, there will be two CSV files that you can work with, one is an aggregate of all the data files together and an other is like a shorter summary csv with some statistics. 

The spreadsheet is just a wrap up of everthing

Thanks for using Covidify 👍
