### ISSUE TITLE
I was missing logscale

### ISSUE THREAD

**Issue by rdorsch** [AaronWard/covidify#32]
**Is your feature request related to a problem? Please describe.**
Since the curves are supposed to be exponential, log scale for the y axis seems to be adequate.

Here is some local modification which worked for me:

rd@h370:~/tmp.nobackup/git/covid-19-analysis$ git diff src/covidify
diff --git a/src/covidify/data_visualization.py b/src/covidify/data_visualization.py
index 89db5c6..9ceae9c 100644
--- a/src/covidify/data_visualization.py
+++ b/src/covidify/data_visualization.py
@@ -95,6 +95,7 @@ def create_trend_line(tmp_df, date_col, col, col2, col3, fig_title, country):
     fig, ax = plt.subplots(figsize=(20,10))
     tmp_df.groupby([date_col])[[col, col2, col3]].sum().plot(ax=ax, marker='o')
     ax.set_title(create_title(fig_title, country))
+    ax.set_yscale('log')
     fig = ax.get_figure()
     fig.savefig(os.path.join(image_dir, create_save_file(col, country, 'trendline')))
 
@@ -102,6 +103,7 @@ def create_bar(tmp_df, col, rgb, country):
     fig, ax = plt.subplots(figsize=(20,10))
     tmp = tmp_df.groupby(['date'])[[col]].sum()
     ax.set_title(create_title(col, country))
+    ax.set_yscale('log')
     tmp.plot.bar(ax=ax, rot=45, color=rgb)
     fig = ax.get_figure()
     fig.savefig(os.path.join(image_dir, create_save_file(col, country, 'bar')))
@@ -110,6 +112,7 @@ def create_stacked_bar(tmp_df, col1, col2, fig_title, country):
     tmp_df = tmp_df.set_index('date')
     fig, ax = plt.subplots(figsize=(20,10))
     ax.set_title(create_title(fig_title, country))
+    ax.set_yscale('log')
     tmp_df[[col2, col1]].plot.bar(ax=ax,
                                   rot=45,
                                   stacked=True)
rd@h370:~/tmp.nobackup/git/covid-19-analysis$ 

a parameter for pipeline.sh certainly would be better.

I saw the you have a log jupyter notebook, which might do the same, but I did not get it working....

**Comment by AaronWard** [comment]
> Since the curves are supposed to be exponential, log scale for the y axis seems to be adequate.

I am working on that right now coincidentally :)
Next release to have a graph which shows the logarithmic growth of the top `N` countries.

Should have the newest release by tomorrow

**Comment by AaronWard** [comment]
@rdorsch Log plot in the newest release
