### ISSUE TITLE
Improve default path for the output data

### ISSUE THREAD

**Issue by Armag67** [AaronWard/covidify#38]
Hello,
It should be better to not hard code the default path for the output data as you do with:
`/Users/award40/Desktop/covidify-output/` it can't work on Linux and could mislead Windows users.
I think it's better to use: `os.path.expanduser("~")` to find the user's home on Windows, Linux or Mac systems and then the `platform.system()` function to choice the good user's desktop folder name.
Otherwise, thank you for this nice work, it works very well under Linux.

**Comment by AaronWard** [comment]
@Armag67 Great suggestion! I will add it into the newest release soon

Thanks very much

**Comment by Armag67** [comment]
I think that the `tempfile` module is also great for a cross-platform way of getting temp directory. I didn't test it.
But, I often use the `GLib.get_user_special_dir()` function in Linux to find the good name of the user's directories in his locale language.
